# Generated by Django 4.1.1 on 2022-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_category_options_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='number_of_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
